In [18]:
import pandas as pd
import numpy as np

In [19]:
teams_df = pd.read_csv('data/teams.csv')
teams_df.tail()

Team_Id      Team_Name
359     1460      Wright St
360     1461        Wyoming
361     1462         Xavier
362     1463           Yale
363     1464  Youngstown St

In [20]:
tourney_df = pd.read_csv('data/TourneyDetailedResults.csv')
teams_df = pd.read_csv('data/Teams.csv')
reg_season_df = pd.read_csv('data/RegularSeasonCompactResults.csv')
team_dict = dict(zip(teams_df['Team_Id'].values, teams_df['Team_Name'].values))
tourney_df['Wteam_name'] = tourney_df['Wteam'].map(team_dict)
tourney_df['Lteam_name'] = tourney_df['Lteam'].map(team_dict)

print('================================================')
print('Tournament data:')
print('================================================')
print(tourney_df.head(10))
print('================================================')
print('Teams data:')
print('================================================')
print(teams_df.head(10))
print('================================================')
print('Season data:')
print('================================================')
print(reg_season_df.head(10))


Tournament data:
   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot  Wfgm  Wfga  \
0    2003     134   1421      92   1411      84    N      1    32    69   
1    2003     136   1112      80   1436      51    N      0    31    66   
2    2003     136   1113      84   1272      71    N      0    31    59   
3    2003     136   1141      79   1166      73    N      0    29    53   
4    2003     136   1143      76   1301      74    N      1    27    64   
5    2003     136   1163      58   1140      53    N      0    17    52   
6    2003     136   1181      67   1161      57    N      0    19    54   
7    2003     136   1211      74   1153      69    N      0    20    47   
8    2003     136   1228      65   1443      60    N      0    24    56   
9    2003     136   1242      64   1429      61    N      0    28    51   

      ...       Lfta  Lor  Ldr  Last  Lto  Lstl  Lblk  Lpf     Wteam_name  \
0     ...         31   17   28    16   15     5     0   22  UNC Asheville   
1  

In [36]:
def features(id1, id2, season, flip):
    f1 = []
    f2 = []
    wins = reg_season_df.loc[valid & in_reg_season[season], 'Wteam'].value_counts()
    f1.append(wins[id1])
    f2.append(wins[id2])
    
    if flip:
        return f2+f1
    else:
        return f1+f2

In [40]:
print(features(1242, 1260, 2015, 0))

[26, 17]


In [48]:
tourney_df.shape

(847, 36)

In [50]:
f = np.zeros((tourney_df.shape[0],2))
print(f)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [45]:
print(tourney_df.loc[0, 'Season'])
print(tourney_df.loc[0, 'Wteam'])
print(tourney_df.loc[0, 'Lteam'])

2003
1421
1411


In [23]:
seasons = tourney_df['Season'].unique()

In [5]:
in_reg_season = dict(zip(seasons, [reg_season_df['Season'] == i for i in seasons]))
in_tourney_season = dict(zip(seasons, [tourney_df['Season'] == i for i in seasons]))
valid = reg_season_df['Wteam'] != 0

In [6]:
tourney2015 = tourney_df[in_tourney_season[2015]]
season_wins = reg_season_df.loc[valid & in_reg_season[2015], 'Wteam'].value_counts()
tourney2015['Wwins'] = tourney2015['Wteam'].map(season_wins)
tourney2015['Lwins'] = tourney2015['Lteam'].map(season_wins)
tourney2015 = tourney2015.replace(np.nan, 0)
tourney2015.head()

/Users/dtamayo/miniconda2/envs/ml/lib/python3.5/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/dtamayo/miniconda2/envs/ml/lib/python3.5/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot  Wfgm  Wfga  \
780    2015     134   1214      74   1264      64    N      0    26    53   
781    2015     134   1279      94   1140      90    N      0    36    80   
782    2015     135   1173      56   1129      55    N      0    20    42   
783    2015     135   1352      81   1316      77    N      0    28    62   
784    2015     136   1112      93   1411      72    N      0    32    53   

     ...    Ldr  Last  Lto  Lstl  Lblk  Lpf     Wteam_name     Lteam_name  \
780  ...     27    15   17     5     3   25        Hampton      Manhattan   
781  ...     32    22   15     0     2   23    Mississippi            BYU   
782  ...     19    10    9     5     1   18         Dayton       Boise St   
783  ...     28    15   18     1     4   23  Robert Morris  North Florida   
784  ...     11     5    9     5     3   19        Arizona    TX Southern   

     Wwins  Lwins  
780     16     19  
781     20     23  
782     25     23  
783     19     20  
784     31     22  

[5 rows x 38 columns]

In [7]:
d = {'Wwins':tourney2015['Wwins'], 'Lwins':tourney2015['Lwins']}
df = pd.DataFrame(data=d)
df.head(10)

Lwins  Wwins
780     19     16
781     23     20
782     23     25
783     20     19
784     22     31
785     26     26
786     20     22
787     21     22
788     23     21
789     23     23

In [8]:
rands = np.random.randint(2,size=df.shape[0])
randscomp = 1-rands

In [14]:
print(rands)

[1 1 1 0 1 1 1 0 0 1 1 0 1 1 0 0 1 1 1 1 0 0 1 1 0 0 1 0 0 0 0 1 1 1 0 1 0
 0 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 0 0 0 1 1 1 1 0 0 0 0 1]


In [9]:
x = [df.iloc[i,rands[i]] for i in range(df.shape[0])]
y = [df.iloc[i,randscomp[i]] for i in range(df.shape[0])]
print(x[6:10])
print(y[6:10])
print(rands[6:10])
d2 = {'wins1':x, 'wins2':y, 'Winner':randscomp}
df2 = pd.DataFrame(data=d2)
print(df2.head())

[22, 21, 23, 23]
[20, 22, 21, 23]
[1 0 0 1]
   Winner  wins1  wins2
0       0     16     19
1       0     20     23
2       0     25     23
3       1     20     19
4       0     31     22


In [10]:
X = df2.iloc[:,1:].values
y = df2.iloc[:,0].values

In [46]:
print(X)

[[16 19]
 [20 23]
 [25 23]
 [20 19]
 [31 22]
 [26 26]
 [22 20]
 [21 22]
 [23 21]
 [23 23]
 [34 16]
 [22 20]
 [24 20]
 [29 23]
 [26 23]
 [25 18]
 [20 26]
 [23 26]
 [32 19]
 [21 20]
 [22 25]
 [19 29]
 [31 21]
 [21 23]
 [21 26]
 [19 24]
 [27 25]
 [21 23]
 [23 30]
 [24 22]
 [17 24]
 [25 20]
 [29 21]
 [23 23]
 [20 27]
 [31 20]
 [23 31]
 [22 34]
 [32 20]
 [24 26]
 [29 22]
 [20 18]
 [23 21]
 [21 23]
 [29 25]
 [21 31]
 [30 24]
 [23 29]
 [22 25]
 [23 27]
 [27 26]
 [31 24]
 [31 21]
 [23 34]
 [29 27]
 [24 31]
 [23 29]
 [20 31]
 [24 20]
 [23 22]
 [34 29]
 [31 31]
 [31 29]
 [24 23]
 [23 29]
 [34 31]
 [29 31]]


In [11]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)

In [12]:
from sklearn import svm
model = svm.SVC()
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [13]:
from sklearn import metrics
y_pred = model.predict(X_test)
print(metrics.accuracy_score(y_test, y_pred))

0.592592592593
